export const CONTRACTORLIST_FETCH_REQUEST = 'CONTRACTORLIST_FETCH_REQUEST';
export const CONTRACTORLIST_FETCH_SUCCESS = 'CONTRACTORLIST_FETCH_SUCCESS';
export const CONTRACTORLIST_FETCH_FAIL = 'CONTRACTORLIST_FETCH_FAIL';

export const CONTRACTOR_FETCH_REQUEST = 'CONTRACTOR_FETCH_REQUEST';
export const CONTRACTOR_FETCH_SUCCESS = 'CONTRACTOR_FETCH_SUCCESS';
export const CONTRACTOR_FETCH_FAIL = 'CONTRACTOR_FETCH_FAIL';

export const CONTRACTOR_CREATE_REQUEST = 'CONTRACTOR_CREATE_REQUEST';
export const CONTRACTOR_CREATE_SUCCESS = 'CONTRACTOR_CREATE_SUCCESS';
export const CONTRACTOR_CREATE_FAIL = 'CONTRACTOR_CREATE_FAIL';

export const CONTRACTOR_UPDATE_REQUEST = 'CONTRACTOR_UPDATE_REQUEST';
export const CONTRACTOR_UPDATE_SUCCESS = 'CONTRACTOR_UPDATE_SUCCESS';
export const CONTRACTOR_UPDATE_FAIL = 'CONTRACTOR_UPDATE_FAIL';

export const CONTRACTOR_DELETE_REQUEST = 'CONTRACTOR_DELETE_REQUEST';
export const CONTRACTOR_DELETE_SUCCESS = 'CONTRACTOR_DELETE_SUCCESS';
export const CONTRACTOR_DELETE_FAIL = 'CONTRACTOR_DELETE_FAIL';

export const CONTRACTOR_RESET_REDIRECT = 'CONTRACTOR_RESET_REDIRECT';
