export const CONTACT_FORM_POST_REQUEST = 'CONTACT_FORM_POST_REQUEST';
export const CONTACT_FORM_POST_SUCCESS = 'CONTACT_FORM_POST_SUCCESS';
export const CONTACT_FORM_POST_FAIL = 'CONTACT_FORM_POST_FAIL';
export const CONTACT_FORM_POST_RESET = 'CONTACT_FORM_POST_RESET';
