export const EMPLOYEELIST_FETCH_REQUEST = 'EMPLOYEELIST_FETCH_REQUEST';
export const EMPLOYEELIST_FETCH_SUCCESS = 'EMPLOYEELIST_FETCH_SUCCESS';
export const EMPLOYEELIST_FETCH_FAIL = 'EMPLOYEELIST_FETCH_FAIL';
