export const EMPLOYEELIST_FETCH_REQUEST = 'EMPLOYEELIST_FETCH_REQUEST';
export const EMPLOYEELIST_FETCH_SUCCESS = 'EMPLOYEELIST_FETCH_SUCCESS';
export const EMPLOYEELIST_FETCH_FAIL = 'EMPLOYEELIST_FETCH_FAIL';

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_ADD_ROLE_REQUEST = 'USER_ADD_ROLE_REQUEST';
export const USER_ADD_ROLE_SUCCESS = 'USER_ADD_ROLE_SUCCESS';
export const USER_ADD_ROLE_FAIL = 'USER_ADD_ROLE_FAIL';

export const USER_DELETE_ROLE_REQUEST = 'USER_DELETE_ROLE_REQUEST';
export const USER_DELETE_ROLE_SUCCESS = 'USER_DELETE_ROLE_SUCCESS';
export const USER_DELETE_ROLE_FAIL = 'USER_DELETE_ROLE_FAIL';

export const USER_RESET_REDIRECT = 'USER_RESET_REDIRECT';

export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL';

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
