export const JOB_CREATE_REQUEST = 'JOB_CREATE_REQUEST';
export const JOB_CREATE_SUCCESS = 'JOB_CREATE_SUCCESS';
export const JOB_CREATE_FAIL = 'JOB_CREATE_FAIL';

export const JOBLIST_FETCH_REQUEST = 'JOBLIST_FETCH_REQUEST';
export const JOBLIST_FETCH_SUCCESS = 'JOBLIST_FETCH_SUCCESS';
export const JOBLIST_FETCH_FAIL = 'JOBLIST_FETCH_FAIL';

export const JOB_FETCH_REQUEST = 'JOB_FETCH_REQUEST';
export const JOB_FETCH_SUCCESS = 'JOB_FETCH_SUCCESS';
export const JOB_FETCH_FAIL = 'JOB_FETCH_FAIL';

export const JOB_UPDATE_REQUEST = 'JOB_UPDATE_REQUEST';
export const JOB_UPDATE_SUCCESS = 'JOB_UPDATE_SUCCESS';
export const JOB_UPDATE_FAIL = 'JOB_UPDATE_FAIL';

export const JOB_DELETE_REQUEST = 'JOB_DELETE_REQUEST';
export const JOB_DELETE_SUCCESS = 'JOB_DELETE_SUCCESS';
export const JOB_DELETE_FAIL = 'JOB_DELETE_FAIL';

export const JOB_RESET_REDIRECT = 'JOB_RESET_REDIRECT';
