export const REPORT_EMPLOYEES_TIMESHEET_REQUEST = 'REPORT_EMPLOYEES_TIMESHEET_REQUEST';
export const REPORT_EMPLOYEES_TIMESHEET_SUCCESS = 'REPORT_EMPLOYEES_TIMESHEET_SUCCESS';
export const REPORT_EMPLOYEES_TIMESHEET_FAIL = 'REPORT_EMPLOYEES_TIMESHEET_FAIL';
