export const TIMESHEET_REQUEST = 'TIMESHEET_REQUEST';
export const TIMESHEET_SUCCESS = 'TIMESHEET_SUCCESS';
export const TIMESHEET_FAIL = 'TIMESHEET_FAIL';

export const TIMESHEET_CREATE_DAY_REQUEST = 'TIMESHEET_CREATE_DAY_REQUEST';
export const TIMESHEET_CREATE_DAY_SUCCESS = 'TIMESHEET_CREATE_DAY_SUCCESS';
export const TIMESHEET_CREATE_DAY_FAIL = 'TIMESHEET_CREATE_DAY_FAIL';

export const TIMESHEET_DELETE_DAY_REQUEST = 'TIMESHEET_DELETE_DAY_REQUEST';
export const TIMESHEET_DELETE_DAY_SUCCESS = 'TIMESHEET_DELETE_DAY_SUCCESS';
export const TIMESHEET_DELETE_DAY_FAIL = 'TIMESHEET_DELETE_DAY_FAIL';
