export const TIMESHEET_REQUEST = 'TIMESHEET_REQUEST';
export const TIMESHEET_SUCCESS = 'TIMESHEET_SUCCESS';
export const TIMESHEET_FAIL = 'TIMESHEET_FAIL';

export const TIMESHEET_CREATE_ENTRY = 'TIMESHEET_CREATE_ENTRY';
export const TIMESHEET_DELETE_ENTRY = 'TIMESHEET_DELETE_ENTRY';
